name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Scalafmt Check
        run: sbt scalafmtCheckAll
      - name: "aetherDeploy Scripted"
        run: sbt aetherDeploy/scripted
    # Handle gpg signed stuff
